apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ralphhumbertoambereggapisources 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ralphhumbertoambereggapisources 
    spec:
      containers:
        - name: ralphhumbertoambereggapisources 
          image: acrrrdevamberegg.azurecr.io/ralphhumbertoambereggapisources
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: transportservice-front
annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    ports:
    - port: 80
    targetPort: 8080
selector:
    app: transportservice-front