apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ralphhumbertoambereggapisources 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ralphhumbertoambereggapisources 
    spec:
      containers:
        - name: ralphhumbertoambereggapisources 
          image: acrrrdevamberegg.azurecr.io/ralphhumbertoambereggapisources
          ports:
          - containerPort: 8080
