apiVersion: v1
kind: Service
metadata:
    name: ralphhumbertoambereggapisources
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "api-ingress-subnet"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
    selector:
        app: ralphhumbertoambereggapisources